version: '3'
services:
  api:
    build: .
    ports:
      - 2500:2500
    depends_on:
      - mongo
    environment:
      - PORT=2500
      - MONGODB_CNN=mongodb://mongo:27017/TarjetasBuses
  mongo:
    image: mongo
    ports:
      - 27017:27017